### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by manuelkoester** [golubevcg/hip_file_diff_tool#1]
Hey!

This is a really cool project and I might want to contribute / build upon the tool in the future so it can also diff hdas or other things like potentially having a CLI mode. But as it is unfortunately missing a license I am not really confident doing so.
Would it be possible for you to add an open source license to this project?  
I can recommend the `Apache license 2.0` as it is [widely used in our industry](https://github.com/AcademySoftwareFoundation/aswf-sample-project/blob/main/LICENSE) and causes no fuss for legal entities. There are a couple of github pages around this topic, too:
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository
https://choosealicense.com/

Thank you!
Manuel

**Comment by golubevcg** [comment]
Hello Manuel!

Thank you for your message; I would happily appreciate any contribution.
I updated the repository and added Apache 2.0 licensing information to the master branch.
