### ISSUE TITLE
Shell error when comparing unsupported files

### ISSUE THREAD

**Issue by doruchan** [golubevcg/hip_file_diff_tool#5]
Hello,

thanks for making this tool, it's super useful!
One thing I noticed is that when you try to compare files with unsupported extensions, it doesn't raise a warning but it raises an exception:

```
Traceback (most recent call last):
  File "/home/dev/hip_file_diff_tool/ui/hip_file_diff_window.py", line 445, in handle_compare_button_click
    self.houdini_comparator.compare()
AttributeError: 'NoneType' object has no attribute 'compare'
```

If you like I can easily implement the warning box and send you a pull request.

cheers

**Comment by golubevcg** [comment]
Hey!
Thank you so much for contributing to this tool; I appreciate it.

Yeah, this is my bad - I probably missed it. if I remember correctly, I had a similar message box dialogue previously, but probably during the latest refactoring, it was missed somewhere. I will do my best to merge both commit the next week!
